# Site settings
# GitHub Pages compatible Jekyll config

# Update these for your brand
 title: "TNT Marketing Consultants, LLC."
 description: "Expert consulting that turns complexity into clarity and results."
 url: "https://tntmarketingconsultants.com"
 baseurl: "" # e.g. /my-site if publishing to a project page

# Author/owner
 author:
  name: "Tim Bryant Principal/Owner"
  email: "tjbryant.tnt@gmail.com"
  twitter: ""
  linkedin: ""

# Theme and plugins
 markdown: kramdown
 plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
 collections:
  posts:
   output: true

# Build settings
 exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - scripts
  - node_modules

# Defaults
 defaults:
  - scope:
     path: ""
     type: "posts"
    values:
     layout: post
  - scope:
     path: ""
     type: "pages"
    values:
     layout: page

# Navigation (used by includes/nav.html)
 nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Services"
    url: "/services/"
  - title: "Testimonials"
    url: "/testimonials/"
  - title: "Blog"
    url: "/blog/"
  - title: "Contact"
    url: "/contact/"

# Branding
 brand:
  primary_color: "#C81E2A" # deeper red from logo
  secondary_color: "#0F172A" # near-black for headings
  accent_color: "#E98A00" # richer orange/yellow accent
  light_color: "#F3F0EA" # slightly darker light background
  dark_color: "#0B0F16"
  font_sans: "Inter, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif"
  font_serif: "Georgia, Cambria, 'Times New Roman', Times, serif"

permalink: pretty

sitemap:
  filename: sitemap.xml
  exclude:
    - /assets/
  include_posts: true
